# ════════════════════════════════════════════════════════
# Sikar District (Rajasthan) — Villages, Towns & Dhanis
# ════════════════════════════════════════════════════════
# Used for ADDRESS auto-suggest, the same way common_names.py
# powers NAME auto-suggest. Source: Census of India 2011 village
# directory, all 6 tehsils of Sikar district (Sikar, Danta Ramgarh,
# Fatehpur, Lachhmangarh, Neem Ka Thana, Sri Madhopur).
#
# NOTE: This covers official revenue villages (which already include
# most named "Ki Dhani" / "Ka Bas" hamlets that have their own census
# code). Very small, informal dhanis with no separate census code are
# NOT covered — add them to EXTRA_LANDMARKS below as you encounter them.
# ════════════════════════════════════════════════════════

VILLAGES_BY_TEHSIL = {
    "Sikar": [
        "Aheeron Ka Bas","Ajeetpura","Akwa","Amarpura","Anokhoo","Antri",
        "Arjunpura","Aspura","Badalwas","Badhadar","Bagriyon Ki Dhani","Bajaj Gram",
        "Bajor","Balaji Ka Nada","Balloopura","Balrampura","Baral","Beri",
        "Bhadwasi","Bhagowa","Bhairoopura","Bhairoopura","Bhajangarh","Bharkasli",
        "Bhawanipura","Bheekhanwasi","Bhojyada","Bhookhron Ka Bas","Bhoowala","Bhoya",
        "Bidoli","Bijarniyon Ki Dhani","Binjasi","Bootoli","Bosana","Chainpura",
        "Chandeli Ka Bas","Chandpura","Charan Ka Bas","Charanwas","Chelasi","Chena Ram Ka Bas",
        "Chokha Ka Bas","Chooroli","Dab Panora","Dadiya","Dadli","Dasa Ki Dhani",
        "Daulatpura","Deeppura","Deeppura Charnan","Deogarh","Devlanada","Dhadel Nagar",
        "Dhaka Ki Dhani","Dhani Chooroli","Dhani Fatehsingh","Dhani Kanolai","Dhani Salamsingh","Dhani Sawairam",
        "Dhani Takhran","Dhaninathawatan","Dharamshala","Dhod","Dhokar","Dinarpura",
        "Doogoli","Doojod","Dulhepura","Dulla Ki Dhani","Durgapura","Fakeerpura",
        "Fatehpura","Ganeshpura","Gokulpura","Goru Ka Bas","Gothra Bhookran","Gothra Tagalan",
        "Gumana Ka Bas","Gunathoo","Gungara","Gurha Kalan","Gurha Khurd","Hameerpura",
        "Hardayalpura","Haripura","Harsh","Hatyaj","Heeramal Nagar","Hukampura",
        "Jachas","Jagatpura","Jagmalpura","Jassoopura","Jerthi","Jheegar Bari",
        "Jheegar Chhoti","Jurathra","Kadma Ka Bas","Kaharo Ki Dhani","Kajlo Ki Dhani","Kala Khet",
        "Kanwarpura","Kanwarpura","Kashi Ka Bas","Kasli","Katrathal","Kesar Nagar",
        "Khakholi","Kharsadoo","Khori Brahmanan","Khori Doongar","Khurd","Kirdoli",
        "Koleera","Krishannagar","Kudan","Kudli","Kundalpur","Kundalpur Dakshin",
        "Kushalpura","Ladwa","Lakheepura","Laxman Ka Bas","Losal Chhoti","Madhopura",
        "Mahla Ki Dhani","Mailasi","Majipura","Maliyon Ki Dhani","Malkera","Mandawara",
        "Mandoli","Mandota","Molyasi","Mordoonga","Mukandpura","Mundwara",
        "Nada Ki Dhani","Nagwa","Nani","Neem Nadya","Netarwas","Ola Ki Dhani",
        "Palasara","Palthana","Palwas","Pardoli Bari","Pardoli Chhoti","Pewa",
        "Phagalwa","Piplya Nagar","Piprali","Poora Ki Dhani","Pooranpura","Puran Bari",
        "Puran Chhoti","Purohit Ka Bas","Raghunathgarh","Rajpura","Rambaxpura","Ramnagar",
        "Rampura","Ramu Ka Bas","Ranawali Dhani","Raseedpura","Rewasi","Rooppura",
        "Sabalpura","Sakrai","Samrathpura","Santoshpura","Sanwaloda Dhaylan","Sanwaloda Ladkhani",
        "Sanwaloda Purophitan","Sarwari","Sewa","Sewad Bari","Sewad Chhoti","Shahpura",
        "Shastrinagar","Shivnagar","Shivsinghpura","Shyamgarh","Shyampura","Sihot Bari",
        "Sihot Chhoti","Sikar","Singhasan","Singrawat","Sob","Sotya Ka Bas",
        "Sujanpura","Swarooppura","Tajsar Karnawatan","Tajsar Khejdoliyan","Tanaja Ki Dhani","Tarpura",
        "Tatanwa","Tetli Nagar","Thorasi","Todi Madhopura","Vikas Nagar",
    ],
    "Danta Ramgarh": [
        "Abhaipura","Adarsh Nagar","Aheer Ka Bas","Ajabpura","Akhepura","Akhepura",
        "Aloda","Amanipura","Amarpura","Amarpura","Anantpura","Badhala Ki Dhani",
        "Bagadiyon Ka Bas","Bagario Ka Bas","Baidh Ki Dhani","Bajyawas","Baloopura","Balyawas",
        "Banathala","Banoora","Bar Ka Charanwas","Barsinghpura","Basri Kalan","Basri Khurd",
        "Bay","Beniyon Ka Bas","Bhagatpura","Bhagatpura","Bhagwan Pura","Bhairoonagar",
        "Bharija","Bhawanipura","Bheema","Bheerana","Bhoja Ki Dhani","Bhoordon Ka Bas",
        "Bubana","Buchyasi","Burdakon Ki Dhani","Chainpura","Chainpura","Chak",
        "Chak Badiya","Chak Bharija No.1","Chak Bharija No.2","Chak Chihala","Chak Dhedi","Chak Geeliya",
        "Chak Gogawas","Chak Kailash","Chak Khandelsar","Chak Kikraliya","Chak Kumliwala","Chak Ladhana",
        "Chak Majipura","Chak Mitai","Chak Sunderpura","Chak Tilokpura","Chak Turkiya","Chandeli Ka Bas",
        "Chandrasinghpura","Chihala","Chimanpura","Chirasara","Dalatpura","Danji Ka Bas",
        "Dansroli","Danta","Dantla","Daulpura","Dhaka Ki Dhani","Dhani Chetandas",
        "Dheejpura","Dheengpur","Dholasari","Doodwa","Dookiya","Dulhepura",
        "Ganeshpura","Ganora","Gila Ki Dhani","Godiawas","Gogawas","Gopinath Pura",
        "Gordhanpura","Goriya","Goriya","Gowati","Gumanpura","Gumanpura",
        "Guwardi","Gyandas Pura","Hanuman Nagar","Hanuman Pura","Hanumanpura","Hanumanpura",
        "Haripura","Heerwas","Hindala Ka Bas","Indrapura","Jaloond","Jana",
        "Jawaharnagar","Jeenmata","Jeenwas","Jhamawas","Jhun Ka Bas","Jivanpura",
        "Jivanpura","Josiyon Ki Dhani","Kabariya Was","Kailash","Kalyanpura","Kankra",
        "Kantiya","Kanwarpura","Karad","Karanpura","Kariron Ki Dhani","Karni Pura",
        "Keero Ki Dhani","Keriya","Kerpura","Kerpura Charanwas","Keshav Ka Bas","Khachariya Was",
        "Khandelsar","Khanri","Khariyawas","Khatiwas","Khatiwas","Khatoo",
        "Khichron Ki Dhani","Khokhron Ka Bas","Khood","Khora","Kikraliya","Kishanpura",
        "Kochhor","Kuli","Kunwalsar","Kushalpura","Lachhmanpura","Ladhana",
        "Ladpur","Lambanagar","Lami Ki Dhani","Lamiyan","Laxmi Pura","Likhma Ka Bas",
        "Losal","Madni","Maganpura","Magra","Magrasi","Majipura",
        "Maksoodpura","Mandha","Mandha Surera","Mandoli","Mei","Miyan Ki Dhani",
        "Mohanpura","Motipura","Motlawas","Mudiyawas","Nada","Nada Charanwas",
        "Nakyawali","Nangal","Nausal","Naya Bas","Nayabas","Neemawas",
        "Neemera","Pachar","Palsana","Papdion Ki Dhani","Parasrampura","Pragatinagar",
        "Pratappura","Prathiveraj Ka Bas","Prempura","Premsinghpura","Prithvipura","Punyana",
        "Rad Ki Dhani","Raghunathpura","Raghunathpura","Raipura","Raiwasa","Rajanpura",
        "Rajpura","Rajpura","Ralawata","Ramgarh","Ramjipura","Ramnagar",
        "Rampura","Ramsingh Pura","Ranoli","Rar Ki Dhani","Reta","Roopgarh",
        "Rooppura","Rulana","Sajjanpura","Samarthpura","Samer","Sami",
        "Sangalya","Sangarwa","Sanwalpura","Sawaipura","Sawant Ka Bas","Sesam",
        "Sheeshyoo","Sherpura","Shiv Singh Pura","Shivbhajanpura","Shivkrishnanagar","Shyam Nagar",
        "Shyami Ki Dhani","Shyampura","Shyampura","Sitarampura","Sri Rampura","Sujawas",
        "Sukhpura","Sulyawas","Sundariya","Sundarpura","Surat Ram Ki Dhani","Surera",
        "Tambakhoopura","Tehat","Tilokpura","Tipaniya Ki Dhani","Tuli Ka Charanbas","Tulsirampura",
        "Udaipura","Umara","Vijaipura","Vijay Nagar","Vijaypura","Vindayak Puri",
    ],
    "Fatehpur": [
        "Alafsar","Almas","Asas","Athwas","Bagas","Bagdoda",
        "Bairas","Balod Bari","Balod Bhakharn","Balod Chhoti","Bari","Bathod",
        "Bavla","Beer Fatehpur","Beswa","Bhagasara","Bhakharwasi","Bheechri",
        "Bheekamsara","Bhojdesar","Bibipur Bara","Bibipur Chhota","Biraniya","Chacheewad Bara",
        "Chacheewad Chhota","Chuwas","Dabri","Dadunda","Dantru","Daulatabad",
        "Deenarpura","Deenwaladkhani","Dewas","Dhakali","Dhakasa","Dhandhan",
        "Dhani Baijnath","Dhani Barwan","Dhani Chatardas","Dhani Dhedi","Dhani Hattidan Charan","Dhani Kalyanpura",
        "Dhani Lawanda","Dhani Pooniyan","Dhani Ridmal","Dhani Sunda","Fadanpura","Fatehpur",
        "Gangapura","Gangyasar","Garandwa","Garinda","Godiya Bara","Godpura",
        "Goras","Goriya Chhota","Govindpura With Hardayalpura","Gudrawas","Hardayalpura","Harsawa Bara",
        "Harsawa Chhota","Hetamsar","Hirna","Hodsar","Hudera","Jalalsar",
        "Jaleu","Jethwan Ka Bas","Jugalpura","Kalyanpura","Kangansar","Karanga Bara",
        "Karanga Chhota","Kayamsar","Khonta Ki Dhani","Khotiya","Khuri","Kishanpura",
        "Kolayat","Lawanda","Madhopura","Mandela Bara","Mandela Chhota","Mardatoo Bari",
        "Mardatoo Chhoti","Marothpura","Nabipura","Nagardas","Nangali","Nari",
        "Narsara","Narsara Hardayalpura","Naya Bas","Neema Ki Dhani","Nethwa","Palas",
        "Ramgarh","Rampura","Ramsisar","Rasoolpur","Rinau","Rohal",
        "Rookansar","Roopnagar","Rosawa","Rughnathpura","Sadeensar","Sahabsar",
        "Sahnoosar","Sanjhasar","Sardarpura","Sawai Laxmanpura","Sawaroopsar","Shekhisar",
        "Sigaro Ki Dhani","Swami Ki Dhani","Tajsar","Takhalsar","Thedi","Theemoli",
        "Thethaliya","Thithawata Bodiya","Thithawata Peeran","Tihawali","Tihay","Udansar",
        "Udansari",
    ],
    "Lachhmangarh": [
        "Alakhpura Bogan","Alakhpura Godaran","Antroli","Badusar","Bagri","Bagriyon Ka Bas",
        "Bairas","Bajroli","Bala Ka Bas","Balaran","Banai","Basni",
        "Basni","Bathoth","Batranau","Bau","Beedasar","Beedsar",
        "Beerodi Bari","Beerodi Chhoti","Bhagoo Mil Ka Bas","Bhairoo Pura","Bhakharo Ki Dhani","Bhaoji Ki Dhani",
        "Bhilunda","Bhojasar Bara","Bhojasar Chhota","Bhoodha Ka Bas","Bhooriyan Ki Dhani","Bhooriyo Ka Bas",
        "Bhuma Bara","Bhuma Chhota","Bochi","Bodlasi","Boojiyanau","Chainpura",
        "Chak Beerodi","Charan Ka Bas","Chhinchhas","Churi Miyan","Dagra","Dalmas",
        "Dantujala","Deenwa Jatan","Deewanji Ka Bas","Devra","Dhahar Ka Bas","Dhanani",
        "Dhani Bajaron","Dhani Charan","Dhani Charan","Dhani Kriparam","Dhani Lalana","Dhani Mangaldas",
        "Dhani Ridmal","Dhani Teeba","Dhanichaindas","Dholas","Dholpaliya","Dishnau",
        "Doodwa","Doongarwas","Dotasara","Fadanpura","Ganeri","Garoda",
        "Ghana","Ghassu","Ghiraniya Bara","Ghiraniya Chhota","Hameerpura","Hapas",
        "Jaitpura","Jajod","Jakhla","Jaloo","Jasrasar","Jeoli",
        "Jhadhewa","Jhajhar","Jhilmil","Jogiyon Ka Bas","Juliyasar","Kachhwa",
        "Kalwa","Kalyanpura","Kandlau","Kantewa","Kaswali","Khaliya Nau",
        "Khatipura","Kheechdo Ki Dhani","Kheenwasar","Kheerwa","Kheri Dookiya","Kheri Radan",
        "Khoru","Khuri Bari","Khuri Chhoti","Kirdoli Bari","Kirdoli Chhoti","Koka Ki Dhani",
        "Kumas Jageer","Kumas Jatan","Lachhmangarh","Lalasi","Madhopura","Madhopura",
        "Madhopura Ghassu Ka Bas","Malsi Bas","Manasi","Manasi Goran","Manasiya","Mangloona",
        "Meelon Ki Dhani","Mirand","Mirjwas","Nangal","Narayan Ka Bas","Narodara",
        "Narsas","Nasanwa","Nechhwa","Olagarh","Pacharon Ki Dhani","Palri",
        "Panlawa","Patoda","Peepli","Poonani","Pooniyan Ka Bas","Posani",
        "Pratappura","Purohiton Ka Bas","Rahnawa","Rajas","Rajpur","Ramchandra Ka Bas",
        "Ramnagar","Ramsingh Pura","Ramsinghpura","Rinu","Roroo Bari","Roroo Chhoti",
        "Rulyana Mali","Rulyana Patti","Rulyani","Sahid J.P.Nagar","Sankhoo","Sanwali",
        "Sethon Ki Dhani","Sewdara","Shekhiwas","Shyorana Ka Bas","Sigdola Bara","Sigdola Chhota",
        "Singodara","Singodari","Sola","Suthoth","Sutod","Swami Ki Dhani",
        "Swami Ki Dhani","Tiroki Bari","Tiroki Chhoti","Tirwa","Tunwa","Turkasiya",
        "Vijaipura","Yalsar",
    ],
    "Neem Ka Thana": [
        "Aagri","Agawari","Ajmeri","Antala","Avinashi","Baghpat Nagar",
        "Bagrawa","Bagwala","Bakshipura","Ballabh Das Pura","Balloopura","Bandhawala",
        "Baniyala","Baniyala Nagar","Barsinghwas","Basri Kalan","Basri Khurd","Bega Ki Nangal",
        "Bhagega","Bhagega Rs","Bhageshwar","Bhagoth","Bhandala","Bhanipura",
        "Bharala","Bharupura","Bheetarli Ganwari","Bhitaro","Bhojmer","Bhomgarh",
        "Bhoodoli","Bihar","Bihari Pur","Bopiya","Bujiyala","Byor",
        "Chak Charawas","Chak Faganwas","Chak Karjo","Chak Mandoli","Chak Ramsinghpura","Chakkola Ki Nangal",
        "Chala","Cheeplata","Chhaja Ki Nangal","Chhapar","Choodla","Dabla",
        "Dalpat Pura","Dareeba","Dayal Ki Nangal","Deepawas","Dehra","Deonagar",
        "Dhandhela","Dhani Aheeran","Dhani Chala","Dokan","Doonga Ki Nangal","Doongar Faganwas",
        "Dungarwas","Faganwas","Fatehpura","Gadrata","Ganeshwar","Ganwali",
        "Ganwari","Ghasi Pura","Ghata Guwar","Godawas","Gopalgarh","Gordhanpura",
        "Govindpura","Guhala","Guwar","Haripura","Harjan Pura","Hasampur",
        "Heera Nagar","Hemrajpura","Hulda Ka Bas","Imloha","Jagat Singh Nagar","Jaitpura",
        "Jassi Ka Bas","Jat Ki Nangal","Jatala","Jatwas","Jeelo","Jhalra",
        "Jhamawas","Jhankra","Jhareenda","Jheerana","Jhitla","Jitala",
        "Jodli","Jugalpura","Jyotiba Nagar","Kachareda","Kairwali","Kala Khera Pratap Pura",
        "Kalakota","Kalakota","Kanthli","Kanwar Ki Nagal","Karjo","Khadag Beejpur",
        "Khadra","Khariya","Khatkar","Khori","Khurdiya","Kishanpura",
        "Kishor Pura","Kishorpura","Kola Ki Nangal","Koliwala","Kotra","Kundala",
        "Kunwara","Kurbara","Kushal Pura","Ladi Ka Bas","Ladiya","Lakhaki Nangal",
        "Luharwas","Mahawa","Malnagar","Mandoli","Mangalpura","Mankri",
        "Manpura","Maukalwas","Mawanda Kalan","Mawanda Khurd","Mawanda Railway Station","Meena Ki Nangal",
        "Mehta Nagar","Mohanpura","Mokalwas Jhareenda","Mothooka","Nanagwas","Napawali",
        "Narayanpura","Narda","Narsingh Puri","Narsinghwala","Natha Ki Nangal","Nathuwala",
        "Naya Bas","Naya Nagar","Neem Ka Thana","Neemod","Nyorana","Palasala",
        "Panchoo Kharkara","Patan","Patel Nagar","Peethalpur","Peetham Puri","Puranabas",
        "Raipur Jageer","Raipur Patan","Raiyan Ka Bas","Rajnagar","Rajpura","Ramlyawas",
        "Rampura","Ramsing Ki Dhani","Ramsinghpura","Ranasar","Ratan Nagar","Rela",
        "Roopawas","Saidala Bhagwanpura","Sakray","Salawali","Sanwal Pura Tanwran","Sanwalpura Shekhawatan",
        "Sedu Ka Bas","Shimli","Shivnagar","Shyalodara","Shyam Pura","Shyama Wali",
        "Sirohi","Tatera","Theekariya","Tigri","Tiwari Ka Bas","Toda",
        "Udaisinghpura",
    ],
    "Sri Madhopur": [
        "Abhawas","Agloi","Ajeetgarh","Anatpura","Arniya","Aspura",
        "Athbigha","Bagariyavas","Bahadurpura","Bahooji Ki Dhani","Balaji Nagar","Balluwali",
        "Balwar","Bamanwas Sajanpura","Bamarda","Baori","Bari Dhani","Bari Dhani Thoi",
        "Barsinghpura","Basri","Bassi","Bhadwari","Bhaira With Luharwas","Bharni",
        "Bhawanipura","Bhojpur","Bhooranpura","Bhopatpura","Biharipur","Bodala",
        "Burja Ki Dhani","Chak Bahooji Ki Dhani","Chak Basri","Chak Chhajna","Chak Dulhepura No. 1","Chak Dulhepura No.2",
        "Chak Hod","Chak Jairampura","Chak Jaswantpura","Chak Khandela No.1","Chak Khandela No.2","Chak Khatundra",
        "Chak Kishanpura","Chak Mau","Chak Udaipura","Chakroyal","Charanwas Gyandhyan Ka Bas","Charanwas Bhopat Ka Bas",
        "Charanwas Gangabishan Ka Bas","Chaukri","Cheelawali","Chhajna","Chhara","Chomu Purohitan",
        "Dadiyarampura","Dahar Kanwat","Dangion Ka Bas","Daulatpura","Dayra","Derawali",
        "Derawalidhani","Devipura","Devipura","Dhabanwali","Dhalyavas","Dhani Choudhariya Wali",
        "Dhani Gumansingh","Dhani Jhajhdiya","Dhani Jodhawali","Dhani Karmli","Dharmpura","Dheerajpura",
        "Divrala","Doodhwalon Ka Bas","Dulhepura","Dulthana","Fatehpura","Fatehpura Bhomiyan",
        "Garh Bhopji","Garh Taknet","Garhi Khanpur","Geedawala","Ghasseepura","Ghatamdaswali",
        "Girdhari Singh Ka Bas","Gokul Ka Bas","Gomawali","Gopalpura","Gopalpura","Goriyan",
        "Govindpura","Gurara","Gurha","Guwariya","Gyanpura","Hameerpura Kalan",
        "Hameerpura Khurd","Hanspur","Hanuman Nagar","Hardas Ka Bas","Haripura","Hathideh",
        "Hathora","Hod","Holiya Ka Vas","Jairampura","Jaitusar","Jajod",
        "Jakhera","Jalalpur","Jankipura","Jaswantpura","Jharli","Jorawar Nagar",
        "Jugalpura","Jugrajpura","Jyotiba Nagar","Kali Khera","Kaliyavas","Kalyanpura",
        "Kalyanpura Thoi","Kancharra Kanchanpur","Kanwarpura","Kanwat","Karadka","Karoi",
        "Kasarda","Kerpura","Khandela","Khanipura","Khatundra","Khemraj Ka Bas Charanwas",
        "Kheri Charnan","Khiroti Manrooppura","Khurampura","Kishanpura","Kolwa","Kotri Shimarla",
        "Kotri Dhaylan","Kotri Luharwas","Krishannagar","Krishannagar","Ladpur","Lakhni",
        "Lalsar","Lapuwa","Leela Ki Dhani Thoi","Lisariya","Loharwara","Madho Ka Bas",
        "Mahroli","Mahron Ki Dhani","Majisahab Ki Dhani","Malakali","Malikpur","Mandoosya",
        "Mangarh","Mau","Meghpura","Modyadi","Mundru","Nalot",
        "Nangal","Nangal Bhim","Nare","Nathoosar","Nawlai","Neemki",
        "Nehron Ki Dhani","Nehron Ki Dhani Bhanipura","Nimera","Norangpura","Padampura","Paniharwas",
        "Parasrampura","Paroda","Patwari Ka Bas","Peeploda Ka Bas","Peerawali","Phootala",
        "Pratappura","Prithvipura","Pujari Ka Bas","Purohit Ka Bas","Ralawata","Ramdas Ka Bag",
        "Ramnagar","Ramnagar","Rampura","Rampura","Ranipura","Ratanpura",
        "Reengus","Rooppura Udalvas","Royal","Salawali","Saledipura","Saledipura",
        "Salwari","Samotaka Bas","Samrathpura","Santoshpura","Sanwatpura Jaita Ki Dhani","Sargoth",
        "Sathiya Vas","Sawaipura Pujari Ka Bas","Seel Ki Bara","Seelpur","Seepur","Sevli",
        "Sewa Ki Dhani","Shahpura","Sherpura","Shimarla Kotri","Shimarla Jageer","Shivpura",
        "Shivram Ka Bas","Shola","Shyam Nagar","Sihori","Soorpura","Sothaliya",
        "Sri Madhopur","Srimadhopur","Suhagpura","Sujana","Sukhpura","Sukhsingh Ka Bas",
        "Sulel","Surani","Suratram Ka Bas","Tapiplya","Teekamnagar","Theekariya Raisinghpura",
        "Thoi","Tilokpura","Tiwari Ki Dhani","Udaipura","Vijaipura",
    ],
}

# Extra well-known landmarks / pilgrimage towns / localities that
# locals commonly use in addresses (may not match exact census spelling).
EXTRA_LANDMARKS = [
    "Khatu Shyamji","Salasar","Harshnath","Jeenmata","Ganeshwar","Lohargal","Raghunathgarh"
]

# ── Flat lookup used by the autosuggest endpoint ──
# normalized_name -> list of (canonical_name, tehsil) tuples
# (kept as a list because the same village name can exist in
# more than one tehsil/gram panchayat in the district)
def _normalize(s):
    return " ".join(s.lower().strip().split())

VILLAGE_LOOKUP = {}
for _tehsil, _names in VILLAGES_BY_TEHSIL.items():
    for _n in _names:
        _key = _normalize(_n)
        VILLAGE_LOOKUP.setdefault(_key, [])
        if (_n, _tehsil) not in VILLAGE_LOOKUP[_key]:
            VILLAGE_LOOKUP[_key].append((_n, _tehsil))
for _n in EXTRA_LANDMARKS:
    _key = _normalize(_n)
    VILLAGE_LOOKUP.setdefault(_key, [])
    if (_n, "Sikar District") not in VILLAGE_LOOKUP[_key]:
        VILLAGE_LOOKUP[_key].append((_n, "Sikar District"))
